# Generated by Django 4.2.7 on 2023-11-27 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokers.status'),
        ),
    ]
