# Generated by Django 4.2.7 on 2023-11-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='days_since_invoiced',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
