# Generated by Django 4.2.7 on 2023-11-29 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0003_invoice_invoiced_date_invoice_paid_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceChange',
            new_name='InvoiceChangeHistory',
        ),
    ]
