# Generated by Django 4.2.7 on 2023-11-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_rename_invoicechange_invoicechangehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicechangehistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
